/*************************************************************************//**
 *****************************************************************************
 * @file   clock.c
 * @brief  
 * @author Forrest Y. Yu
 * @date   2005
 *****************************************************************************
 *****************************************************************************/

#include "type.h"
#include "stdio.h"
#include "const.h"
#include "protect.h"
#include "string.h"
#include "fs.h"
#include "proc.h"
#include "tty.h"
#include "console.h"
#include "global.h"
#include "proto.h"


/*****************************************************************************
 *                                clock_handler
 *****************************************************************************/
/**
 * <Ring 0> This routine handles the clock interrupt generated by 8253/8254
 *          programmable interval timer.
 * 
 * @param irq The IRQ nr, unused here.
 *****************************************************************************/
PUBLIC void clock_handler(int irq)
{
	if (++ticks >= MAX_TICKS)
		ticks = 0;

	if (p_proc_ready->ticks)
		p_proc_ready->ticks--;

	if (p_proc_ready->time_remain)
		p_proc_ready->time_remain--;

	if (key_pressed)
		inform_int(TASK_TTY);

	if (k_reenter != 0) {
		return;
	}

	struct proc* p;
	for(p = &FIRST_PROC; p <= &LAST_PROC; p++) { //search new arrived process
		if(p->p_flags == 0 && !p->if_arrive) {
			p->queuenum = 1;
			p->time_remain = FIRST_ROUND_SIZE;
			p->if_arrive = 1;
			p->status = 2; //ready
		}
	}

	if(p_proc_ready->ticks<1){ //finish
		p_proc_ready->queuenum = 3;
		p_proc_ready->time_remain = 0;
	}
	if(p_proc_ready->time_remain > 0) //remain time slice
		return;
	if(p_proc_ready->queuenum == 1) {
		p_proc_ready->time_remain = SECOND_ROUND_SIZE;
		p_proc_ready->queuenum++;
	}else if(p_proc_ready->queuenum == 2) {
		p_proc_ready->time_remain = THIRD_ROUND_SIZE;
		p_proc_ready->queuenum++;
	}else if(p_proc_ready->queuenum == 3) {
		p_proc_ready->time_remain = THIRD_ROUND_SIZE;
	}

	schedule();

}

/*****************************************************************************
 *                                milli_delay
 *****************************************************************************/
/**
 * <Ring 1~3> Delay for a specified amount of time.
 * 
 * @param milli_sec How many milliseconds to delay.
 *****************************************************************************/
PUBLIC void milli_delay(int milli_sec)
{
        int t = get_ticks();

        while(((get_ticks() - t) * 1000 / HZ) < milli_sec) {}
}

/*****************************************************************************
 *                                init_clock
 *****************************************************************************/
/**
 * <Ring 0> Initialize 8253/8254 PIT (Programmable Interval Timer).
 * 
 *****************************************************************************/
PUBLIC void init_clock()
{
        /* 初始化 8253 PIT */
        out_byte(TIMER_MODE, RATE_GENERATOR);
        out_byte(TIMER0, (u8) (TIMER_FREQ/HZ) );
        out_byte(TIMER0, (u8) ((TIMER_FREQ/HZ) >> 8));

        put_irq_handler(CLOCK_IRQ, clock_handler);    /* 设定时钟中断处理程序 */
        enable_irq(CLOCK_IRQ);                        /* 让8259A可以接收时钟中断 */
}


